
train:
  input_size: 6
  hidden_layer_size: 32
  num_layers: 1
  output_size: 1
  dropout_rate: 0.4
  iter_var: 5
  scheduler: ReduceLROnPlateau
  clip_value: 1.0
  MCD: false
  num_epochs: 50
  n_epochs_stop: 10
  batch_size: 16

optim:
  lr: 0.0001

data:
  scaler: minmax
  data_path: "data/SP500_stock_prices_log_clean_3monthreturn.csv"
  date_splits:
    - '2018-10-01'
    - '2019-01-01'
    - '2019-04-01'
    - '2019-07-01'
    - '2019-10-01'
  exp_output_dir: "exp_base"