
train:
  input_size: 6
  hidden_layer_size: 32
  num_layers: 1
  output_size: 1
  dropout_rate: 0.4
  num_epochs: 50
  patience: 3
  n_epochs_stop: 5
  batch_size: 16

optim:
  lr: 0.001

data:
  data_path: "data/SP500_stock_prices_log_clean_3monthreturn.csv"
  date_splits:
    - 2018-10-01
    - 2019-01-01
    - 2019-04-01
    - 2019-07-01
    - 2019-10-01
  exp_output_dir: "exp_base"